### ISSUE TITLE
release v0.1.0 white paper

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdakits-whitepaper#9]
Publicly release the 0.1.0 version of the MDAKits White Paper

- [x] all authors signed off #8 
- [x] deposited with DOI (figshare — or elsewhere?) #2 
- [x] updated copy in [MDAKits](https://github.com/MDAnalysis/MDAKits/tree/main/paper/whitepaper), see https://github.com/MDAnalysis/MDAKits/issues/4
- [ ] blog post https://github.com/MDAnalysis/MDAnalysis.github.io/issues/241
- [ ] tweet
